[package]
name = "iobewi-esp-config-space"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "ESP NVS adapter for IOBEWI ConfigSpace"
keywords = ["esp32", "configuration", "nvs", "embedded", "no-std"]
categories = ["embedded", "hardware-support", "no-std"]

[features]
default = []
esp32c3 = [
  "iobewi-esp-flash/esp32c3",
  "iobewi-esp-nvs/esp32c3",
]
esp32s3 = [
  "iobewi-esp-flash/esp32s3",
  "iobewi-esp-nvs/esp32s3",
]

[dependencies]
iobewi-config-space = { git = "https://github.com/iobewi/iobewi", rev = "d61b9265b92912d034a31e346dbf261d9488b8e5" }
iobewi-esp-flash = { path = "../../hardware/flash" }
iobewi-esp-nvs = { path = "../../hardware/nvs" }
esp-nvs = "0.5.0"
log = { version = "0.4.29", default-features = false }
